import Header from "@/components/Header";
import PostProvider from "@/context/PostProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          <PostProvider>{children}</PostProvider>
        </main>
      </body>
    </html>
  );
}
